FROM postgres:${PG_VERSION}-alpine

# Install dependencies
RUN apk add --no-cache clang-analyzer clang perl make musl-dev gcc curl;

# Environment
ENV LANG=C.UTF-8 PGDATA=/pg/data

# Make directories
RUN	mkdir -p ${PGDATA} && \
	mkdir -p /pg/testdir

# Grant privileges
RUN	chown postgres:postgres ${PGDATA} && \
	chown postgres:postgres /pg/testdir && \
	chmod a+rwx /usr/local/lib/postgresql && \
	chmod a+rwx /usr/local/share/postgresql/extension

COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

ADD . /pg/testdir
WORKDIR /pg/testdir

USER postgres
ENTRYPOINT /run.sh
